# Basic
title = "BlackPhillip"
baseURL = "https://blackphillip.netlify.app"
theme = "vno-hugo"

# Pagination
paginate = 10
paginatePath = "page"


[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']


[outputs]
  home = ["HTML", "RSS"]

[menu]

# Buttons____________________________
  [[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "/#projects"
    weight = 1
    [menu.main.params]
      type  = "button"
      class = "projects-button"

  [[menu.main]]
    name = "Shop"
    identifier = "shop"
    url = "/#shop"
    weight = 1
    [menu.main.params]
      type  = "button"
      class = "shop-button"
# Products___________________________
  [[menu.main]]
    name = "TSOL Kenaz"
    identifier = "tsolkenaz"
    url = "/geometriques/#tsolkenaz"
    weight = 1
    [menu.main.params]
      series = "T'SOL"
      model  = "Kenaz"
      type   = "product"

  [[menu.main]]
    name = "TSOL Laguz"
    identifier = "tsollaguz"
    url = "/geometriques/#tsollaguz"
    weight = 1
    [menu.main.params]
      series = "T'SOL"
      model  = "Laguz"
      type   = "product"

  [[menu.main]]
    name = "TSOL Uruz"
    identifier = "tsoluruz"
    url = "/geometriques/#tsoluruz"
    weight = 1
    [menu.main.params]
      series = "T'SOL"
      model  = "Uruz"
      type   = "product"

  [[menu.main]]
    name = "TSOL Algiz"
    identifier = "tsolalgiz"
    url = "/geometriques/#tsolalgiz"
    weight = 1
    [menu.main.params]
      series = "T'SOL"
      model  = "Algiz"
      type   = "product"


[taxonomies]
    tag = "tags"

[params]
author = "A94"
titleA = "Black"
titleB = "PhiλЛip"
subtitle = "As above, so below" #Deprecated
description = "Blog, portfolio and project documentation."
welcomeMessage = "Greetings traveler"
custom_css = ["css/custom.css"]
# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = ""

[params.comment]
disqus = "blackphillipblog"
duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
[params.comment.gitalk]
ID = ""
secret = ""
repo = ""
owner = ""

[params.social]
# weibo = "onevcat"
github = "ambrosino94"
# twitter = "onevcat"
# gplus = "107108267983477358170"
mail = "ambrosinotech@gmail.com"
ig = "ambrosino94"

[params.ga]
ID = "your_ga_id"
host = "your_host"

# The blog button should not be removed.
[params.blogButton]
title = "Blog"
description = "Visit blog"

[permalinks]
posts = "/:month/:year/:title/"
