name: GStarted

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Env Secrets
        env:
          SNIPCART_KEY: "test"
        run:
          echo env test
