name: GStarted

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Env Secrets
        env:
<<<<<<< HEAD
          SNIPCART_KEY: "test"
        run:
          echo env test
=======
          SNIPCART_KEY: test
        run: |
          echo Env test

          
    
>>>>>>> 57150a339bf6f4b22e2ad37836e019e4d6e7d0a6
